export const site = {
  name: "Revizio",
  domain: "revizioapp.com",
  url: "https://revizioapp.com",
  supportEmail: "support@revizioapp.com",
  privacyEmail: "support@revizioapp.com",
  legalEntity: "Revizio App",
  legalForm: "Société",
  legalAddress: "31700 Blagnac, France",
  legalCountry: "France",
  supportDelay: "sous 3 jours ouvrés",
  appStoreUrl: "https://apps.apple.com/us/app/revizio/id6761366726",
  playStoreUrl: null as string | null,
  androidComingSoon: true,
  lastUpdated: "12/05/2026",
  locale: "fr_FR",
  language: "fr",
  tagline: "Apprends en jouant",
  description:
    "Revizio transforme un thème ou un cours en jeu IA en quelques secondes. 8+ jeux IA, une aventure de plus de 180 niveaux à travers 6+ mondes, un défi par jour. Sur iOS.",
  shortDescription:
    "Apprends en jouant. 8+ jeux IA, 180+ niveaux d'aventure. Sur iOS.",
  keywords: [
    "Revizio",
    "application apprentissage",
    "jeux IA éducatifs",
    "quiz IA",
    "pendu",
    "bingo apprentissage",
    "mots croisés",
    "aventure éducative",
    "apprendre en jouant",
    "culture générale",
    "app étudiants",
    "iOS apprentissage",
  ],
  legalLinks: {
    privacy: "/privacy",
    terms: "/terms",
    support: "/support",
    deleteAccount: "/delete-account",
  },
};
