export const site = {
  name: "Revizio",
  domain: "revizioapp.com",
  url: "https://revizioapp.com",
  supportEmail: "support@revizioapp.com",
  privacyEmail: "support@revizioapp.com",
  legalEntity: "Revizio App",
  legalForm: "Société",
  legalAddress: "31700 Blagnac, France",
  legalCountry: "France",
  supportDelay: "sous 3 jours ouvrés",
  appStoreUrl: "APP_STORE_URL",
  playStoreUrl: "PLAY_STORE_URL",
  lastUpdated: "19/04/2026",
  locale: "fr_FR",
  language: "fr",
  tagline: "Comprends. Teste-toi. Retiens.",
  description:
    "Revizio transforme un sujet en fiche, quiz, examen ou rappels intelligents. Un compagnon d’apprentissage premium pour étudiants, adultes en reconversion et curieux.",
  shortDescription:
    "Un sujet, une fiche, un quiz ou un examen — en quelques secondes. Sur iOS et Android.",
  keywords: [
    "application apprentissage",
    "app révision",
    "fiche de révision IA",
    "quiz IA",
    "examen blanc",
    "mémoriser un sujet",
    "rappels intelligents",
    "mémo structuré",
    "scan de cours",
    "app étudiants",
    "adulte reconversion",
    "apprendre en autonomie",
    "culture générale",
    "préparer un concours",
    "Revizio",
  ],
  // Deep-linked URLs from the app (constants/legal-links.ts)
  legalLinks: {
    privacy: "/privacy",
    terms: "/terms",
    support: "/support",
    deleteAccount: "/delete-account",
    subscriptions: "/subscriptions",
  },
};
